---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: 'test/integration/data_bags'

platforms:
  - name: ubuntu-14.04
    driver_config:
      privileged: true

suites:
  - name: base
    run_list: [
      'recipe[rubygems]'
    ]
  - name: balancer
    run_list: [
      'recipe[rubygems]',
      'recipe[rubygems-balancer]'
    ]
    attributes:
      dev_mode: true
  - name: database
    run_list: []
  - name: app
    run_list: [
      'recipe[rubygems]',
      'recipe[rubygems-app]'
    ]
    attributes:
      dev_mode: true
  - name: cache
    run_list: [
      'recipe[rubygems-cache]'
    ]
