default_environments:
  - common
  - staging
environment_groups:
  all:
    - common
    - staging
    - production
version_change_threshold: 2
preserve_constraint_operators: true
always_promote_remote: true
skip_berkshelf: false
json_options:
  indent: "    "
plugins:
  git:
    enabled: true
  foodcritic:
    enabled: true
    tags:
      - FC003
      - FC011
  rubocop:
    enabled: true
